name: WorkflowFilters and Activities

on:
  workflow_dispatch:
#  schedule:
#    - cron: "*/59 * * * *"
  push: 
# 2 filters - branches-ignore and branches. cannot use both of them ff     
    #branches-ignore
    #    - feature/*
    #    - test/**
    branches:
        - main
        - '!feature/*' #ignoring pushing to any branch name starting with feature 
  pull_request:
    types:
      - opened
      - closed
    paths-ignore: #workflow will only run when a pull request that includes a change on any file other than REAME
      - README.md
    branches:
      - main 

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - $ {{ github.event_name }}
